---
 name: Gather basic system information on Windows
  hosts: all
  tasks:
    - name: Gather Windows facts
      win_facts:

    - name: Display OS information
      debug:
        msg: "Operating System: {{ ansible_facts.os_family }} {{ ansible_facts.os_version }}"

    - name: Display hostname
      debug:
        msg: "Hostname: {{ ansible_facts.hostname }}"

    - name: Display CPU architecture
      debug:
        msg: "CPU Architecture: {{ ansible_facts.processor_architecture }}"

    - name: Display total memory
      debug:
        msg: "Total Memory: {{ ansible_facts.memtotal_mb }} MB"
